# Quick Help Without Googling

In [10]:
firefly = {'type': 'TV Show', 'amazingness': 9001}

To get exhaustive help on all methods applicable to any Python object, pass the object to `help()`.  

Note: In the resulting output, it is generally safe to ignore the methods with leading underscores.  These are methods written for internal use in implementing the "public" methods.  You should focus on the methods without underscore (the "public" methods), examples of which include (for dicts): `.keys()`, `.values()`, `.pop()`, etc. 

In [11]:
help(firefly)

Help on dict object:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      True if D has a key k, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize s

`dir()` shows a list of all associated methods, without including any documentation for any of them.

In [12]:
dir(firefly)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

# Dicts

## `.get()`

The `.get()` method is very handy when you want to try to access keys in a dict that may not exist yet.

In [4]:
firefly = {'type': 'TV Show'}

In [36]:
firefly['year']

KeyError: 'year'

`firefly['year']` fails as expected because the `year` key does not exist . But, `firefly.get('year')` executes and returns `None`.

In [9]:
print(firefly.get('actors'))

None


But the cool thing is that you can make `.get()` return a more useful value than `None` as well. E.g., you could return `Missing Attribute` whenever someone tries to access a non-existant key:

In [37]:
firefly.get('actors', 'Missing Attribute')

'Missing Attribute'

The `.get()` method is useful when you loop over a list of "potential keys" and try accessing their values in a dict.  Note that `.get()` does not modify the dict `firefly` in any way - the key `actor` is still missing there.

## Building Counters

In [15]:
my_list = ['one', 'two', 'two', 'three', 'three', 'three', 'four', 'four', 'four', 'four']

### Easiest Solution - `Counter`

Note that the `collections` module is part of the standard Python library.

In [14]:
from collections import Counter

In [18]:
my_counter = Counter(my_list)
my_counter

Counter({'one': 1, 'two': 2, 'three': 3, 'four': 4})

In [21]:
my_counter['three']     # the Counter object acts similar to a dict

3

In [24]:
my_counter.items()

dict_items([('one', 1), ('two', 2), ('three', 3), ('four', 4)])

### Hacky, Inefficient, *One-liner* Dict Comprehension

If you're doing this in an interview and they ask you specifically to NOT use `Counter`, this is an alternative:

In [25]:
my_counter = {item:my_list.count(item) for item in my_list}
my_counter

{'one': 1, 'two': 2, 'three': 3, 'four': 4}

Issues with this approach in an interview setting: 

(1) `count()` is an $O(n)$ operation.  This solution is therefore $O(n^2)$
(2) The interviewer may potentially disallow using the `count()` method. 

Nonetheless, this might be a reasonable placeholder that you can come back to later and switch out with something else.

### Efficient, Simple Counter

In [74]:
my_counter = {}
for key in my_list:
    my_counter[key] = my_counter.get(key, 0) + 1    

my_counter

{'one': 1, 'two': 2, 'three': 3, 'four': 4}

This solution has only one loop, and with the `get()` method being $O(1)$, the total time complexity for this solution is $O(n)$.

# Lists

In [3]:
my_list = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight']

## Access Every nth List Element

Access every element at an even index number:

In [11]:
my_list[1::2]

['two', 'four', 'six', 'eight']

Access every element at an odd index number:

In [13]:
my_list[::2]

['one', 'three', 'five', 'seven']

More generally, access every $n^{th}$ element from the list:

In [14]:
n = 3
my_list[::n]

['one', 'four', 'seven']

## List Reversal

This is an extension of the idea in the previous section.  Use Python's list slicing feature, with `-1` causing a reversal in the direction of increments.

In [2]:
my_list[::-1]

['five', 'four', 'three', 'two', 'one']

# Numpy

In [1]:
import numpy as np

## Array Slicing

### Lost Dimensions on Slicing

In [10]:
my_array = np.random.random((4, 3, 2))

In [11]:
my_array.shape

(4, 3, 2)

In [14]:
# subset the slice containing the first element from the 2nd dimension
my_sub_array = my_array[:, 0, :]
print(my_sub_array)

[[0.79708087 0.45940686]
 [0.63800715 0.90595981]
 [0.57506334 0.60978485]
 [0.77467899 0.68763552]]


Now, you'd expect the shape of `my_sub_array` to be `(4, 3, 2)` just like `my_array`.  Alas, that's not the case!

In [15]:
my_sub_array.shape

(4, 2)

While slicing an array, whenever you use a fixed position (`0` in case of `my_array[:, 0, :]`) for any dimension, you *lose that dimension* in the result.

Here's how you can avoid this:

In [24]:
my_sub_array = my_array[:, :1, :]   # 0 replaced by :1 which has a similar effect
print(my_sub_array)

[[[0.79708087 0.45940686]]

 [[0.63800715 0.90595981]]

 [[0.57506334 0.60978485]]

 [[0.77467899 0.68763552]]]


In [25]:
my_sub_array.shape    # Voila! No dimension loss!

(4, 1, 2)

## Array Rotation

In [4]:
my_array = np.array([1, 2, 3, 4, 5])

Imagine this array` 1 | 2 | 3 | 4 | 5 ` is written on the side of a merry-go-round.  As the merry-go-round (array) rotates left, the elements on the left of the array disappear and start appearing on the right side.

E.g.:

Rotate the array `right` by `2` positions: Expected Result =  ` 4 | 5 | 1 | 2 | 3 `.

Rotate the array `left` by `1` positions: Result = ` 2 | 3 | 4 | 5 | 1 `.

### with `np.roll`

In [6]:
np.roll(my_array, 2)    # Rotate the array right by 2 positions:

array([4, 5, 1, 2, 3])

In [7]:
np.roll(my_array, -1)    # Rotate the array left by 1 position:

array([2, 3, 4, 5, 1])

In [8]:
# multi-dimenisional cases
my_array_nd = np.array([1,2,3,4,5,6,7,8,9]).reshape(3, 3)

In [14]:
print('original 2-d array: \n', my_array_nd)

original 2-d array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
my_array_nd_rolled = np.roll(my_array_nd, 1, axis=0)
print('rolled 2-d array: \n', my_array_nd_rolled)

rolled 2-d array: 
 [[7 8 9]
 [1 2 3]
 [4 5 6]]
