# Quick Help Without Googling

In [10]:
firefly = {'type': 'TV Show', 'amazingness': 9001}

To get exhaustive help on all methods applicable to any Python object, pass the object to `help()`.  

Note: In the resulting output, it is generally safe to ignore the methods with leading underscores.  These are methods written for internal use in implementing the "public" methods.  You should focus on the methods without underscore (the "public" methods), examples of which include (for dicts): `.keys()`, `.values()`, `.pop()`, etc. 

In [11]:
help(firefly)

Help on dict object:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      True if D has a key k, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize s

Sometimes running something like `help(str)` might spit out a wall of text on your terminal window (when you're running this directly in a terminal, say, in a Coderpad interview).  In such a case you'll have to hold down the down arrow key or the enter key for a painfully long time while you wait for the documentation to scroll down to the method of your interest.  To avoid this, **after running `help(str)`, press `/` followed by the method name (or any term that you're interested in, e.g. `/zfill`) and hit enter - this runs a search of the term you entered after `/` and jumps to the point in the docs matching that term.**

`dir()` shows a list of all associated methods, without including any documentation for any of them.

In [12]:
dir(firefly)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

See all non-internal string methods (those without `__`):

In [1]:
[x for x in dir('fvfv') if '__' not in x]

['capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

For any method you're interested in, you can display the documentation as follows:

In [2]:
# say, you're interested in the 'zfill' method
'x'.zfill.__doc__

'S.zfill(width) -> str\n\nPad a numeric string S with zeros on the left, to fill a field\nof the specified width. The string S is never truncated.'

# Dicts

## `.get()`

The `.get()` method is very handy when you want to try to access keys in a dict that may not exist yet.

In [4]:
firefly = {'type': 'TV Show'}

In [36]:
firefly['year']

KeyError: 'year'

`firefly['year']` fails as expected because the `year` key does not exist . But, `firefly.get('year')` executes and returns `None`.

In [9]:
print(firefly.get('actors'))

None


But the cool thing is that you can make `.get()` return a more useful value than `None` as well. E.g., you could return `Missing Attribute` whenever someone tries to access a non-existant key:

In [37]:
firefly.get('actors', 'Missing Attribute')

'Missing Attribute'

The `.get()` method is useful when you loop over a list of "potential keys" and try accessing their values in a dict.  Note that `.get()` does not modify the dict `firefly` in any way - the key `actor` is still missing there.

## Building Counters

In [15]:
my_list = ['one', 'two', 'two', 'three', 'three', 'three', 'four', 'four', 'four', 'four']

### Easiest Solution - `Counter`

Note that the `collections` module is part of the standard Python library.

In [14]:
from collections import Counter

In [18]:
my_counter = Counter(my_list)
my_counter

Counter({'one': 1, 'two': 2, 'three': 3, 'four': 4})

In [21]:
my_counter['three']     # the Counter object acts similar to a dict

3

In [24]:
my_counter.items()

dict_items([('one', 1), ('two', 2), ('three', 3), ('four', 4)])

### Hacky, Inefficient, *One-liner* Dict Comprehension

If you're doing this in an interview and they ask you specifically to NOT use `Counter`, this is an alternative:

In [25]:
my_counter = {item:my_list.count(item) for item in my_list}
my_counter

{'one': 1, 'two': 2, 'three': 3, 'four': 4}

Issues with this approach in an interview setting: 

(1) `count()` is an $O(n)$ operation.  This solution is therefore $O(n^2)$
(2) The interviewer may potentially disallow using the `count()` method. 

Nonetheless, this might be a reasonable placeholder that you can come back to later and switch out with something else.

### Efficient, Simple Counter

In [74]:
my_counter = {}
for key in my_list:
    my_counter[key] = my_counter.get(key, 0) + 1    

my_counter

{'one': 1, 'two': 2, 'three': 3, 'four': 4}

This solution has only one loop, and with the `get()` method being $O(1)$, the total time complexity for this solution is $O(n)$.

## `defaultdict()`

In [1]:
from collections import defaultdict

To initialize a defaultdict with an integer value (`0`):

In [2]:
d = defaultdict(int)
d['test']

0

To initialize a defaultdict with a custom value, other than `0`:

In [3]:
d = defaultdict(lambda : 17)
d['test']

17

The idea here is that you need to pass a callable function to `defaultdict()` that outputs the default value when the key is not present in the dict.

In [4]:
int()   # note that calling int() returns 0

0

In [6]:
# one more example
d = defaultdict(lambda : [1, 10, 100])
d['test']

[1, 10, 100]

# Lists

In [3]:
my_list = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight']

## Access Every nth List Element

Access every element at an even index number:

In [11]:
my_list[1::2]

['two', 'four', 'six', 'eight']

Access every element at an odd index number:

In [13]:
my_list[::2]

['one', 'three', 'five', 'seven']

More generally, access every $n^{th}$ element from the list:

In [14]:
n = 3
my_list[::n]

['one', 'four', 'seven']

## List Reversal

This is an extension of the idea in the previous section.  Use Python's list slicing feature, with `-1` causing a reversal in the direction of increments.

In [2]:
my_list[::-1]

['five', 'four', 'three', 'two', 'one']

## Flatten Nested Lists

In [4]:
nestedlist = [[1, 2, 3], ['a', 'b', 'c'], ['A', 'B', 'C']]

In [8]:
nestedlist

[[1, 2, 3], ['a', 'b', 'c'], ['A', 'B', 'C']]

In [1]:
from itertools import chain

In [10]:
list(chain.from_iterable(nestedlist))

[1, 2, 3, 'a', 'b', 'c', 'A', 'B', 'C']

# Numpy

In [2]:
import numpy as np

## Looping Over Arrays

You can directly loop over rows of an array easily, without using indices:

In [37]:
my_array_2d = np.array([1,2,3,4,5,6,7,8,9]).reshape(3, 3)
my_array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
for row in my_array_2d:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


To loop over columns, just take the transpose using `.T` and loop over the rows of the transpose.

In [39]:
for col in my_array_2d.T:
    print(col)

[1 4 7]
[2 5 8]
[3 6 9]


### np.ndenumerate

`np.ndenumerate` allows looping over the array and enumerating indices in a concise, clean manner.

In [44]:
for index, value in np.ndenumerate(my_array_2d):
    print('Index: {}, Value: {}'.format(index, value))

Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6
Index: (2, 0), Value: 7
Index: (2, 1), Value: 8
Index: (2, 2), Value: 9


## Array Slicing

### Lost Dimensions on Slicing

In [10]:
my_array = np.random.random((4, 3, 2))

In [11]:
my_array.shape

(4, 3, 2)

In [14]:
# subset the slice containing the first element from the 2nd dimension
my_sub_array = my_array[:, 0, :]
print(my_sub_array)

[[0.79708087 0.45940686]
 [0.63800715 0.90595981]
 [0.57506334 0.60978485]
 [0.77467899 0.68763552]]


Now, you'd expect the shape of `my_sub_array` to be `(4, 3, 2)` just like `my_array`.  Alas, that's not the case!

In [15]:
my_sub_array.shape

(4, 2)

While slicing an array, whenever you use a fixed position (`0` in case of `my_array[:, 0, :]`) for any dimension, you *lose that dimension* in the result.

Here's how you can avoid this:

In [24]:
my_sub_array = my_array[:, :1, :]   # 0 replaced by :1 which has a similar effect
print(my_sub_array)

[[[0.79708087 0.45940686]]

 [[0.63800715 0.90595981]]

 [[0.57506334 0.60978485]]

 [[0.77467899 0.68763552]]]


In [25]:
my_sub_array.shape    # Voila! No dimension loss!

(4, 1, 2)

## Array Rolling with np.roll

In [4]:
my_array = np.array([1, 2, 3, 4, 5])

Imagine this array` 1 | 2 | 3 | 4 | 5 ` is written on the side of a merry-go-round.  As the merry-go-round (array) rotates left, the elements on the left of the array disappear and start appearing on the right side.

E.g.:

Rotate the array `right` by `2` positions: Expected Result =  ` 4 | 5 | 1 | 2 | 3 `.

For a 1-d list, it can be done manually in a one-liner easily, but in an n-dim array, rolling along the mth dim can be easily done by `np.roll`

In [6]:
np.roll(my_array, 2)    # Rotate the array right by 2 positions:

array([4, 5, 1, 2, 3])

Rotate the array `left` by `1` positions: Result = ` 2 | 3 | 4 | 5 | 1 `.

In [7]:
np.roll(my_array, -1)    # Rotate the array left by 1 position:

array([2, 3, 4, 5, 1])

In [5]:
# multi-dimenisional cases
my_array_2d = np.array([1,2,3,4,5,6,7,8,9]).reshape(3, 3)

In [6]:
print('original 2-d array: \n', my_array_2d)

original 2-d array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
my_array_2d_rolled = np.roll(my_array_2d, 1, axis=0)
print('rolled 2-d array: \n', my_array_2d_rolled)

rolled 2-d array: 
 [[7 8 9]
 [1 2 3]
 [4 5 6]]


## Array Rotation

In [19]:
my_array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.rot90(my_array_2d, k=-1)

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

# String Methods

## Convert `"string"` to `['s', 't', 'r', 'i', 'n', 'g']`

In [1]:
list("string")

['s', 't', 'r', 'i', 'n', 'g']

## The `string` Module

In [1]:
import string

Get a string of all letters - both upper and lower case:

In [3]:
string.ascii_letters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

Get a string of all lowercase letters: 

In [4]:
string.ascii_lowercase

'abcdefghijklmnopqrstuvwxyz'

Get a string of all punctuation symbols:

In [5]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

Get a string of all whitespace characters:

In [6]:
string.whitespace

' \t\n\r\x0b\x0c'